postgres-datavolume:
  image: nuxeo/postgres
  volume_driver: convoy-nfs
  volumes:
    - nuxeopg:/var/lib/postgresql/data
  entrypoint: /bin/true
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name

postgres:
  image: nuxeo/postgres
  environment:
    - POSTGRES_USER=nuxeo
    - POSTGRES_PASSWORD=nuxeo    
  labels:
    io.rancher.sidekicks: postgres-datavolume
    io.rancher.container.hostname_override: container_name
  volumes_from:
  - postgres-datavolume

redis:
  labels:    
    io.rancher.container.hostname_override: container_name
  tty: true
  image: redis:3.0.3
  stdin_open: true

nuxeo-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  image: nuxeo
  entrypoint: /bin/true
  volume_driver: convoy-nfs
  volumes:
    - nuxeodata:/data  

nuxeo:
  ports:
  - 8080:8080/tcp
  environment:
    NUXEO_CLID: ${clid}
    NUXEO_PACKAGES: ${packages}
    NUXEO_DB_HOST: postgres
    NUXEO_DB_TYPE: postgresql
  labels:
    io.rancher.sidekicks: nuxeo-datavolume    
    io.rancher.container.hostname_override: container_name
  image: nuxeo
  links:
  - redis:redis
  - postgres:postgres
  volumes_from:
  - nuxeo-datavolume


