.catalog:
  name: "Nuxeo Platform"
  version: "7.10"
  description: |
    Enterprise Content Management 
    Platform for Business Applications
  uuid: nuxeo-0
  questions:
    - variable: clid
      description: "A valid CLID to be able to download packages from Nuxeo Online Services. in the form part1\npart2"
      label: "CLID"
      type: "string"
      required: false
      default: ""
    - variable: "packages"
      type: "string"
      label: "List of Nuxeo packages"
      description: |
        List of Nuxeo packages 
      default: nuxeo-web-mobile nuxeo-drive nuxeo-diff nuxeo-spreadsheet nuxeo-dam nuxeo-template-rendering nuxeo-template-rendering-samples nuxeo-showcase-content
    - variable: "postgres_source"
      description: "Link to Postgres service or stack/service"
      label: "Postgres source"
      type: "service"
      required: true
      default: "Postgres/postgres"
    - variable: "elasticsearch_source"
      description: "Link to elasticsearch service or stack/service"
      label: "Elasticsearch source"
      type: "service"
      required: true
      default: "es/elasticsearch-clients"
    - variable: "elasticsearch_clustername"
      description: "Name of the ES cluster to join"
      label: "ES Cluster Name"
      type: "string"
      required: true
      default: "es"
nuxeo:
  scale: 1
  health_check:
    port: 8080
    # Interval is measured in milliseconds
    interval: 5000
    unhealthy_threshold: 5
    # For TCP, request_line needs to be ''
    # TCP Example: 
    # request_line: ''
    request_line: GET /nuxeo/login.jsp HTTP/1.0
    healthy_threshold: 2
    # Response timeout is measured in milliseconds
    response_timeout: 2000
